name = "MazeGeneration"
uuid = "69c593f6-09be-483e-a797-b209f583db7f"
authors = ["Gruppe 43"]
version = "0.1.0"

[deps]
Test = "b77e0a4c-a3ab-5a33-86ab-337c1bb7b7d0"

[extras]
Test = ["Test"]

[targets]
test = ["Test"]
